name: Docker Image CI for GHCR

on:
  push

jobs:
  Build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push jtr image
        run: |
          docker login --username ${{ secrets.GHCR_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io

          docker build --platform linux/amd64 -t ghcr.io/${{ secrets.GHCR_USERNAME }}/jtr:latest-amd64 .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/jtr:latest-amd64

          docker build --platform linux/arm64 -t ghcr.io/${{ secrets.GHCR_USERNAME }}/jtr:latest-arm64 .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/jtr:latest-arm64
